### ISSUE TITLE
How to create a suitable zst file?

### ISSUE THREAD

**Issue by baoilleach** [martinellimarco/indexed_zstd#12]
The README.md says:

>  IndexedZstdFile will only speed up seeking when there are more than one block, which sadly requires a bit of care in zstd.

Could you elaborate on the specific "bit of care" that's needed? At the zstd command-line, I see options like:
```
--target-compressed-block-size=# : generate compressed block of approximately targeted size
 -B#    : cut file into independent blocks of size # (default: no block)
```
...will one of these options produce the desired result? If so, what would you say is a reasonable blocksize? My only reference is bgzf which uses 65536 bytes.

**Comment by martinellimarco** [comment]
That's really a confusing line I wrote, sorry. I don't recall the exact reason I wrote it that way but all I can think of is that I meant to say that in zstd it's not the default behaviour. I will update the readme.

The block size really depends on the data you are working with and the speed you want to achieve while seeking.

Keep in mind that in zstd each block is independently compressed. It means that no informations is shared between blocks and thus small blocks equals worse compression ratio.

As far as I know the options you pointed out will not create multiple blocks, you can inspect the generated zstd file with `zstd -l <archive.zstd>`

You may want to use [t2sz](https://github.com/martinellimarco/t2sz/) to generate the archives.

65536 bytes is very small and will not give you much in term of compression. Start with a few megabytes.
