### ISSUE TITLE
Providing conda packages

### ISSUE THREAD

**Issue by ap--** [martinellimarco/indexed_zstd#13]
Hello @martinellimarco 

I am starting work on providing conda packages for ratarmount and its dependencies.
Would you be interested in providing indexed_zstd via conda?
If yes, I could offer to create the feedstock repository for you to provide packages via conda-forge. I would also be maintaining this feedstock repository, and (of course) add you as a maintainer too.

For reference, here's the discussion in the downstream repo: https://github.com/mxmlnkn/ratarmount/issues/99

Let me know what you think,
Cheers,
Andreas 😃

**Comment by martinellimarco** [comment]
Hi @ap--, let's do it! :)

My experience with conda is 0 but I'm willing to learn everything that's needed.

Where do we start?

**Comment by ap--** [comment]
Hi @martinellimarco,

Awesome. I will start preparing the feedstock repo for integrating into conda forge. In the meantime it would be great if we could merge #14 to remove the non-standard `--cython` argument. Since pep518 and pep517 are fully supported by pip, cython can be specified as a build requirement and the cpp file doesn't have to be vendored anymore.

**Comment by ap--** [comment]
#14 is not so urgent. I forgot we'd have to do another release just to adhere to good practices. So feel free to decide if and/or when you want to merge #14.

In the meantime, could you comment https://github.com/conda-forge/staged-recipes/pull/21250 here, that you would like to be listed as a maintainer?

**Comment by ap--** [comment]
Also, what's your opinion on having libzstd-seek as its own package in conda?
Are there other downstream tools other than indexed_zstd that depend on libzstd-seek?

**Comment by martinellimarco** [comment]
HI @ap-- ,

I will review #14 this weekend. At a first glance it seems good but I want to test it carefully.

As requested I've commented in https://github.com/conda-forge/staged-recipes/pull/21250 to be a maintainer.

As far as I know libzstd-seek is only used by indexed_zstd which is really not much more than a wrapper around it.
I don't think it's necessary to publish it in conda at this time but I'm by no mean against it if you think there is some need for it. On the contrary, if you think it's needed I will gladly support it.

**Comment by ap--** [comment]
Awesome.


> As far as I know libzstd-seek is only used by indexed_zstd which is really not much more than a wrapper around it.

I think then we'll avoid the overhead of adding it. Because we'd then probably have to dynamically link against it in the conda world. So let's keep it simple. 😃

**Comment by ap--** [comment]
Hi @martinellimarco 

The conda feedstock is now available at https://github.com/conda-forge/indexed_zstd-feedstock
Over the next days the conda-forge migration bots will open PRs in the repo and once merged will provide Python3.11 as well as osx-arm64 builds for indexed_zstd.

Whenever you release a new version to pypi, the conda-forge bots will automatically open a new PR in the feedstock repository to upgrade the version and provide new packages.

In case you want to add a badge to the README, you can use:
```
[![Conda (channel only)](https://img.shields.io/conda/vn/conda-forge/indexed_zstd?label=conda)](https://anaconda.org/conda-forge/indexed_zstd)
```
[![Conda (channel only)](https://img.shields.io/conda/vn/conda-forge/indexed_zstd?label=conda)](https://anaconda.org/conda-forge/indexed_zstd)


If you have any questions, please let me know!

Cheers,
Andreas 😃
