### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by ap--** [martinellimarco/indexed_zstd#15]
Hi @martinellimarco 

I wanted to experiment if it's complicated to provide `indexed_zstd` as windows wheels, and put together a working example. As a disclaimer: my C and windows knowledge is enough to get stuff done for me, but very far from knowing anything about best practices, and/or why some things are done the way they are. 

see:
- https://github.com/ap--/indexed_zstd/tree/windows
- https://github.com/ap--/libzstd-seek/tree/windows

It's just a hack for now, since it assumes that you install and build it in a conda environment.
But it might be a good starting point if there's interest in providing `indexed_zstd` for windows too.

Here's running the test script on windows:

```powershell
(iz) C:\Users\andreas\Development\indexed_zstd\test>python test.py
Block offset completed?:  False
{0: 0, 17: 4, 32: 6, 49: 10, 78: 26}
Block offset completed?:  True
Test reading letters from A to Z
ABCDEFGHIJKLMNOPQRSTUVWXYZ
Tell is 26:  26
Compressed tell is 78:  78
Seeking back to 15
Tell is 15?:  15
Compressed tell is 49:  49
Filesize is 26?  26
Compressed tell is 49:  49
Reading a byte after EOF
Compressed tell is 78:  78
Test reading again, letters from P to Z
QRSTUVWXYZ
Testing set_block_offsets
Block offset completed?:  False
{0: 0, 17: 4, 32: 6, 49: 10, 78: 26}
Block offset completed?:  True
```

To build on windows:
```powershell
git clone --recurse-submodules -b windows https://github.com/ap--/indexed_zstd.git
conda create -n iz python=3.11 zstd conda-build
conda activate iz
pip install ./indexed_zstd
```

I guess if someone is interested and feels more at home in the windows c-extension python world, it should be easy for them to clean this up. (We could then provide windows pkgs in conda-forge too.)

Cheers,
Andreas 😃

**Comment by martinellimarco** [comment]
Hi  Andreas,

thank you! :) I had plans to explore the feasibility of a windows port but I never took the time for it.

I'm in the same boat when it comes to windows programming, I very rarely use windows at all and certainly I'm not knowledgeable about best practices, but I'm sure we can make it work.

I will setup a windows environment the next week to test it but looking at the code it looks promising.

I will investigate how to reproduce the build in github actions too, unless you already have a plan for that.


Kind regards,
Marco

**Comment by ap--** [comment]
Hi Marco,

I think I'm almost there. I added a draft PR with the changes.

Some minor fixes are still needed, and probably a decision needs to be made if indexed_zstd should ship libzstd.dll on windows wheels or not.

Cheers,
Andreas
