### ISSUE TITLE
Missing wheels for macosx_11_0_arm64

### ISSUE THREAD

**Issue by mxmlnkn** [martinellimarco/indexed_zstd#19]
Hey there,

Because of https://github.com/mxmlnkn/ratarmount/issues/135 and https://github.com/martinellimarco/indexed_zstd/issues/17, I would like to ask for publishing new wheels for macosx arm and for Python 3.12. There are arm runners available: [macos-13-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) and [macos-14-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md).

It is confusing that macos-14-latest seems to use macos-14-arm64, but when I try to use macos-14-arm64 directly, then the action doesn't get executed and simply waits for a runner... https://github.com/actions/runner-images/issues/9741

**Comment by martinellimarco** [comment]
Hey, thank you for opening this issue!

I will take the time this weekend to work on it.

**Comment by martinellimarco** [comment]
Fixed in #20
