### ISSUE TITLE
Not compiling w/clang (on Android & Linux)

### ISSUE THREAD

**Issue by danieldjewell** [martinellimarco/indexed_zstd#3]
Related to #2 the issue appears to be not just MacOS but anything based on clang... 

I ran into the issue while compiling w/clang 12 on Android. Complaint about ```-std=c++11``` not being valid for language C. 

By forcing the selection of the configuration for Darwin (by simply adding ```or True``` to line 12... below) compilation succeeded.

https://github.com/martinellimarco/indexed_zstd/blob/f4caf6067b140bfa9ca9872bbd3ccc3763027f7f/setup.py#L12

Perhaps the test shouldn't be platform based but compiler based? [If compiler is clang....]

I can confirm the same error on Debian when the compiler is set to clang instead of gcc/g++... (e.g. ```CC="clang-11" CXX="clang++-11" python setup.py build_ext --cython --inplace```

(I haven't had a chance to test on FreeBSD but since the default compiler is now clang, I would imagine the same issue would exist.)

**Comment by martinellimarco** [comment]
Thank you for reporting this. It didn't occur to me that it was the compiler and not the platform. I will fix it tomorrow.

**Comment by danieldjewell** [comment]
Also just noticed this line as well:

https://github.com/martinellimarco/indexed_zstd/blob/f4caf6067b140bfa9ca9872bbd3ccc3763027f7f/setup.py#L73

Also, a really really strange linking issue - but only on Android? -- the final compilation step (to output the

**Comment by danieldjewell** [comment]
Whoops. Sorry wrong button. 

Also found this line:

https://github.com/martinellimarco/indexed_zstd/blob/f4caf6067b140bfa9ca9872bbd3ccc3763027f7f/setup.py#L73

Also -- really really strange linking issue on what seems to be only Android? (though it could also be clang-12 related... since my testing on x64 Linux was with clang-11) -- During the final linking step to create the python module .so, on Android somehow libzstd.so doesn't get linked - even though it's in the list of libraries... And just changing the order of the libraries manually fixed it. But no error message or anything (until trying to import in python when it complains that it can't find the symbols for libzstd....)

I changed the library order from:
```
clang++ -shared [........] -lm -lzstd -lpython3.9 -lzstd_zeek -o build/lib.linux-aarch64-3.9/indexed_zstd.cpython-39.so
```

to:
```
clang++ -shared [........] -lm -lpython3.9 -lzstd_zeek -lzstd -o  build/lib.linux-aarch64-3.9/indexed_zstd.cpython-39.so
```
