### ISSUE TITLE
Wheels for macOS

### ISSUE THREAD

**Issue by mxmlnkn** [martinellimarco/indexed_zstd#4]
Hello,

Someone had problems installing on macOS, see [here](https://github.com/mxmlnkn/ratarmount/issues/70).

It would be nice if there were wheels for macOS to avoid system prerequisites like zstd being installed.

I extended the Github Workflow CI of `indexed_bzip2` to also create wheels for macOS and Windows. As this repo is based on `indexed_bzip2`, maybe these changes could be pulled to this repo. I could try to open a MR if you want but it might take until next weekend.

**Comment by martinellimarco** [comment]
Hi there,

thank you for reporting this. I'm busy with my job this week but I can work on it this weekend.

I never tried to build this on windows but I will certainly look ad how you did it in `indexed_bzip2` and try to replicate it here, thanks.
