### ISSUE TITLE
Tarfile, seek required arguments.

### ISSUE THREAD

**Issue by codecnotsupported** [martinellimarco/indexed_zstd#9]
```
  File "/.../anaconda3/envs/test/lib/python3.10/tarfile.py", line 2465, in __iter__
    tarinfo = self.next()
  File "/.../anaconda3/envs/test/lib/python3.10/tarfile.py", line 2332, in next
    self.fileobj.seek(self.offset - 1)
  File "indexed_zstd/indexed_zstd.pyx", line 77, in indexed_zstd._IndexedZstdFile.seek
TypeError: seek() takes exactly 2 positional arguments (1 given)
```
Works fine if I manually specify `whence` as 0.

**Comment by martinellimarco** [comment]
I'm not sure how to reproduce the problem but I pushed a branch that I think will fix your issue, can you test it? It's the branch named "fix9"

**Comment by codecnotsupported** [comment]
That fixed it.

**Comment by martinellimarco** [comment]
Can you provide a small code that reproduce the issue? We are discussing the proper solution to adopt but we still can't reproduce the problem. That would be very helpful, thanks!

**Comment by codecnotsupported** [comment]
Good thing you asked, I set-up a test case and realized my mistake when I wrote:
```python
    with IndexedZstdFileRaw(file_str) as file_obj:
        with tarfile.open(fileobj=file_obj) as tar_file:
            pass
```
I was using, `IndexedZstdFileRaw`. Instead of `IndexedZstdFile`.
Apologies for the mix-up. Closing, as it works as intended (I presume).

**Comment by martinellimarco** [comment]
No problem, it's better to have a bug report for a mix-up that not having one in the first place. Besides I think I will patch it anyway.
